openapi: 3.0.0
info:
  title: Browserless.io API
  version: v2
servers:
  - url: https://production-sfo.browserless.io/
  - url: https://production-lon.browserless.io/
paths:
  /config:
    get:
      summary: Get your worker's configuration
      operationId: getWorkerConfig
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          example: MY_API_TOKEN
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowCORS:
                    type: boolean
                  allowFileProtocol:
                    type: boolean
                  allowGetCalls:
                    type: boolean
                  concurrent:
                    type: integer
                  data:
                    type: string
                  debug:
                    type: string
                  errorAlertURL:
                    type: string
                  healthFailureURL:
                    type: string
                  host:
                    type: string
                  maxCPU:
                    type: integer
                  maxMemory:
                    type: integer
                  metricsJSONPath:
                    type: string
                  port:
                    type: integer
                  queued:
                    type: integer
                  queuedAlertURL:
                    type: string
                  rejectAlertURL:
                    type: string
                  retries:
                    type: integer
                  timeout:
                    type: integer
                  timeoutAlertURL:
                    type: string
                  token:
                    type: string
              example:
                allowCORS: true
                allowFileProtocol: false
                allowGetCalls: false
                concurrent: 10
                data: "/tmp/browserless-data-dirs"
                debug: "browserless*,-**:verbose"
                errorAlertURL: null
                healthFailureURL: null
                host: "localhost"
                maxCPU: 99
                maxMemory: 99
                metricsJSONPath: "/tmp/browserless-metrics.json"
                port: 3001
                queued: 10
                queuedAlertURL: null
                rejectAlertURL: null
                retries: 5
                timeout: 30000
                timeoutAlertURL: null
                token: "6R0W53R135510"
tags:
- name: Management-REST-APIs
