openapi: 3.0.0
info:
  title: Browserless API Documentation
  version: v2.0.0
servers:
  - url: https://production-sfo.browserless.io
  - url: https://production-lon.browserless.io

paths:
  /metrics:
    get:
      summary: Fetch metrics
      description: Retrieve an array of session statistics. The data returned will have a maximum date of 1 week.
      parameters:
        - name: token
          in: query
          required: true
          description: API key.
          schema:
            type: string
      responses:
        200:
          description: Array of session statistics
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    error:
                      type: integer
                    maxConcurrent:
                      type: integer
                    queued:
                      type: integer
                    rejected:
                      type: integer
                    running:
                      type: integer
                    sessionTimes:
                      type: array
                      items:
                        type: integer
                    successful:
                      type: integer
                    timedout:
                      type: integer
                    unauthorized:
                      type: integer
                    unhealthy:
                      type: integer
                    maxTime:
                      type: integer
                    meanTime:
                      type: integer
                    minTime:
                      type: integer
                    totalTime:
                      type: integer
                    units:
                      type: integer
                    date:
                      type: integer
                    cpu:
                      type: number
                    memory:
                      type: number
              example:
                - error: 3
                  maxConcurrent: 4
                  queued: 0
                  rejected: 0
                  running: 3
                  sessionTimes: [992, 1041, 802]
                  successful: 0
                  timedout: 0
                  unauthorized: 0
                  unhealthy: 0
                  maxTime: 1041
                  meanTime: 945
                  minTime: 802
                  totalTime: 2835
                  units: 3
                  date: 1709134233732
                  cpu: 0.024877870173220466
                  memory: 0.7784158564199399

  /metrics/total:
    get:
      summary: Fetch total metrics
      description: This route will output a similar payload, but with the total stats of all sessions.
      responses:
        200:
          description: Total session statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: integer
                  maxConcurrent:
                    type: integer
                  queued:
                    type: integer
                  rejected:
                    type: integer
                  running:
                    type: integer
                  sessionTimes:
                    type: array
                    items:
                      type: integer
                  successful:
                    type: integer
                  timedout:
                    type: integer
                  unauthorized:
                    type: integer
                  unhealthy:
                    type: integer
                  maxTime:
                    type: integer
                  meanTime:
                    type: integer
                  minTime:
                    type: integer
                  totalTime:
                    type: integer
                  units:
                    type: integer
                  date:
                    type: integer
                  cpu:
                    type: number
                  memory:
                    type: number
