openapi: "3.0.0"
info:
  title: Browserless.io /scrape API
  version: "2.0"
servers:
  - url: https://production-sfo.browserless.io
  - url: https://production-lon.browserless.io
paths:
  /scrape:
    post:
      summary: Scrape web page
      operationId: scrape
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
            example: MY_API_TOKEN
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              properties:
                url:
                  type: string
                  example: "https://browserless.io/"
                elements:
                  type: array
                  items:
                    type: object
                    properties:
                      selector:
                        type: string
                        example: "h1"
                gotoOptions:
                  type: object
                  properties:
                    timeout:
                      type: integer
                      example: 10000
                    waitUntil:
                      type: string
                      example: "networkidle2"
                waitForTimeout:
                  type: integer
                  example: 1000
                waitForSelector:
                  type: object
                  properties:
                    selector:
                      type: string
                      example: "h1"
                    timeout:
                      type: integer
                      example: 5000
                waitForFunction:
                  type: object
                  properties:
                    fn:
                      type: string
                      example: "async()=>{let t=await fetch('https://jsonplaceholder.typicode.com/todos/1'),e=await t.json();document.querySelector('h1').innerText=e.title}"
                    timeout:
                      type: integer
                      example: 5000
                waitForEvent:
                  type: object
                  properties:
                    event:
                      type: string
                      example: "fullscreenchange"
                    timeout:
                      type: integer
                      example: 5000
      responses:
        "200": 
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        results:
                          type: object
                          properties:
                            attributes:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                    example: "class"
                                  value:
                                    type: string
                                    example: "..."
                            height:
                              type: integer
                              example: 120
                            html:
                              type: string
                              example: "Headless browser automation, without the hosting headaches"
                            left:
                              type: integer
                              example: 32
                            text:
                              type: string
                              example: "Headless browser automation, without the hosting headaches"
                            top:
                              type: integer
                              example: 196
                            width:
                              type: integer
                              example: 736
                        selector:
                          type: string
                          example: "h1"
